integrador/config/routes.rb
Integrador::Application.routes.draw do
  resources :sessions
  resource :dashboard
  resources :courses
  resources :students do
    collection do
      get :search
    end
  end
  
  root :to => "dashboards#show"
end

integrador/app/models/api/authentication.rb
class Api::Authentication < Api::Base

  def self.valid_password?(username, password)
    return false if username.blank? or password.blank?
    request = post("/ei/session", :body => { :username => username, :password => password })
    puts request
    status = request["ei"]["autenticacion"]["status"]
    return false if status != "ok"
    request["ei"]["autenticacion"]["token"]
  end

  private 

end

integrador/app/models/api/base.rb
class Api::Base
  include HTTParty
  base_uri YAML.load_file(Rails.root.join("config/app_config.yml"))["data_source_url"]
end

integrador/app/models/api/course.rb
class Api::Course < Api::Base

  def self.all(token)
    return [] if token.blank?
    request = get("/ei/courses", :query => { :token => token })
    [(request["ei"]["cursos"] || {"curso" => []} )["curso"]].flatten
  end
  
  def self.show(token, course_id)
    return nil if token.blank?
    request = get("/ei/courses/#{course_id}", :query => { :token => token })
    if request["ei"]["curso"]["mensaje"].present?
      raise request["ei"]["curso"]["mensaje"]
    else
      request["ei"]["curso"]["modulo"] = [request["ei"]["curso"]["modulo"]].flatten
      request["ei"]["curso"]
    end
  end

  private 

end

integrador/app/models/api/schedule.rb
class Api::Schedule < Api::Base

  def self.show(token, course_id, group, semester)
    return [] if token.blank? or course_id.blank? or group.blank? or semester.blank?
    request = get("/pa/courses/#{course_id}/schedule", :query => { :token => token, :group => group, :semester => semester })
    begin
      request["pa"]["programacion"]["evaluacion"] || []
    rescue
      raise request["pa"]["curso"]["mensaje"]
    end
  end
end

integrador/app/models/api/student.rb
class Api::Student < Api::Base

  def self.all(token, course_id, group)
    return [] if token.blank? or course_id.blank? or group.blank?
    request = get("/ei/courses/#{course_id}/students", :query => { :token => token, :group => group })
    [request["ei"]["curso"]["estudiante"]].flatten.compact
  end
  
  def self.search(token, name_pattern)
    return [] if token.blank? or name_pattern.blank?
    request = get("/ar/students/search", :query => { :token => token, :name_pattern => name_pattern })
    [request["ar"]["estudiante"]].flatten.compact
  end
  
  
  def self.show(token, student_id)
    return nil if token.blank? or student_id.blank?
    request = get("/ar/students/#{student_id}", :query => { :token => token, :student_id => student_id })
    student = [request["ar"]["estudiante"]].flatten.first
    student["cursos"]["curso"] = [student["cursos"]["curso"]].flatten.compact
    student
  end
end

integrador/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_token, :logged_in?
  before_filter :require_user
    
  protected

  def current_token
    session[:token]
  end
  
  def logged_in?
    current_token.present?
  end
  
  def require_user
    redirect_to new_session_path, :notice => "Tienes que autenticarte primero" unless logged_in?
  end
  

end

integrador/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include CoursesHelper
  
  def show
    @course = Api::Course.show(current_token, params[:id])
    @students = Api::Student.all(current_token, params[:id], params[:group])
    @schedule = Api::Schedule.show(current_token, params[:id], params[:group], current_semester)
  rescue => e
    redirect_to dashboard_path, :alert => e.message
  end
  
end

integrador/app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @courses = Api::Course.all(current_token)
  end
end

integrador/app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController
  skip_before_filter :require_user, :only => [ :new, :create ]
  def new
  end

  def create
    token = Api::Authentication.valid_password?(params[:username], params[:password])
    if token.blank?
      redirect_to new_session_path, :alert => "Credenciales inválidas."
    else
      session[:token] = token
      redirect_to dashboard_path, :notice => "¡Bienvenido, amigo mío!"
    end
  end

  def destroy
    session.delete(:token)
    redirect_to new_session_url, :notice => "Hasta la próxima."
  end
end

integrador/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def search
    @students = Api::Student.search(current_token, params[:name_pattern])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def show
    @student = Api::Student.show(current_token, params[:id])
  end
end

integrador/app/helpers/application_helper.rb
module ApplicationHelper
end

integrador/app/helpers/courses_helper.rb
module CoursesHelper
  def course_title(course, group)
    "#{course["codigo"].upcase} - #{course["nombre"]} - Grupo #{group}"
  end
  
  def current_semester
    year = Date.today.year
    semester = Date.today.month < 7 ? 1 : 2
    "#{year}#{semester}"
  end
  
  def date_distance(some_date)
    prefix = Time.now < some_date ? "Dentro de " : "Hace "
    prefix + time_ago_in_words(some_date)
  end
end

integrador/app/helpers/dashboard_helper.rb
module DashboardHelper
end

integrador/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

integrador/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

integrador/app/helpers/sessions_helper.rb
module SessionsHelper
end

integrador/app/helpers/users_helper.rb
module UsersHelper
end

integrador/app/views/courses/show.html.erb
<% title course_title(@course, params[:group]) %>

<h2>Contenidos</h2>
<ul>
  <% @course["modulo"].each do |mod| %>
    <li>
      <b><%= mod["titulo"] %></b>
      <div>
        <%= mod["descripcion"] %>
      </div>
      <div>
        <%= link_to "(link)", mod["url"] %>
      </div>
    </li>
  <% end %>
</ul>


<h2>Lista de estudiantes</h2>

<%= render "students/students", :collection => @students %>

<h2>Programación semestre <%= current_semester %></h2>

<table class="r">
  <tr>
    <th class="r">Actividad</th>
    <th class="r">Porcentaje</th>
    <th class="r">Fecha</th>
    <th class="r"></th>
  </tr>

  <% @schedule.each do |event| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="r"><b><%= event["tipo"].titleize %></b></td>
      <td class="r"><%= event["porcentaje"] %>%</td>
      <td class="r"><%= l Date.parse(event["fecha"]) , :format => :long %></td>
      <td class="r"><%= date_distance(Date.parse(event["fecha"])) %></td>
    </tr>
  <% end %>
</table>

integrador/app/views/dashboards/show.html.erb
<% title "Mis cursos" %>

<table class="r">
  <tr>
    <th class="r">Código</th>
    <th class="r">Nombre</th>
    <th class="r">Grupo</th>
  </tr>

  <% @courses.each do |course| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="r"><%= course["codigo"].upcase %></td>
      <td class="r"><%= course["nombre"] %></td>
      <td class="r"><%= link_to course["grupo"], course_path(course["codigo"], :group => course["grupo"]) %></td>
    </tr>
  <% end %>
</table>

<h2>Buscar un estudiante</h2>

<div class="center">
  <%= form_tag search_students_path, :method => :get, :remote => true, :id => "search_students_form" do %>
    <%= label_tag :name_pattern, "Parte del nombre" %>
    <%= text_field_tag :name_pattern %>
    <%= submit_tag "Buscar" %>
  <% end %>

  <div class="spinner">
    <%= image_tag "spinner.gif" %>
  </div>

  <div id="search_results">
  </div>
</div>

integrador/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="header">
        <%= link_to_unless_current "Página principal", dashboard_path %>
        <% if logged_in? %>
          | <%= link_to "Salida segura", session_path(:id => "user"), :method => :delete %>
        <% end %>
      </div>

      <hr />

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

integrador/app/views/students/_results.html.erb
<% if @students.empty? %>
  No hay resultados.
<% else %>
  <%= render "students", :collection => @students %>
<% end %>

integrador/app/views/students/_students.html.erb
<table class="r">
  <tr>
    <th class="r">Código</th>
    <th class="r">Nombre</th>
  </tr>

  <% @students.sort_by { |s| s["nombre"] }.each do |student| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="r"><%= link_to student["codigo"], student_path(student["codigo"]) %></td>
      <td class="r"><%= student["nombre"] %></td>
    </tr>
  <% end %>
</table>

integrador/app/views/students/search.html.erb
<% title "Resultados de la búsqueda" %>

<div id="search_results">
  <%= render "results" %>
</div>

<h3>Realizar nueva búsqueda</h3>

<%= form_tag search_students_path, :method => :get do %>
  <%= label_tag :name_pattern, "Parte del nombre" %>
  <%= text_field_tag :name_pattern, params[:name_pattern] %>
  <%= submit_tag "Buscar" %>
<% end %>

integrador/app/views/students/search.js.erb
$("#search_results").fadeOut(function() {
  $(this).html("<%= escape_javascript render("results") %>").fadeIn(function(){
    $(".spinner").slideUp();
  });
});

integrador/app/views/students/show.html.erb
<% title @student["nombre"] %>

<p>
  <b><%= label_tag :code, "Código" %>:</b> <%= @student["codigo"] %>
</p>

<p>
    <b><%= label_tag :code, "Email" %>:</b> <%= mail_to @student["email"] %>
</p>

<p>
  <b><%= label_tag :code, "Teléfono" %>:</b> <%= @student["telefono"] %>
</p>

<h2>Cursos en los que este estudiante está inscrito</h2>

<table class="r">
  <tr>
    <th class="r">Código</th>
    <th class="r">Nombre</th>
    <th class="r">Grupo</th>
  </tr>

  <% @student["cursos"]["curso"].each do |course| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td class="r"><%= course["codigo"].upcase %></td>
      <td class="r"><%= course["nombre"] %></td>
      <td class="r"><%= link_to course["grupo"], course_path(course["codigo"], :group => course["grupo"]) %></td>
    </tr>
  <% end %>
</table>